### ISSUE TITLE
Incorrect adherence to licence terms

### ISSUE THREAD

**Issue by adieyal** [factly/janaganana#9]
Hi

I just had a look at the licence of your codebase and it seems that you have changed the original upstream licence. This is probably accidental but please review the terms of the licence here:
https://github.com/Code4SA/wazimap/blob/master/LICENSE

Specifically, the original MIT licence should refer to Census Reporter. Also, the terms require adequate attribute to Census Reporter, Wazimap, Media Monitoring Africa and Code for South Africa. These licence terms cannot be removed.

While we're overjoyed that you have used Census Reporter / Wazimap for Counting India we feel that it is only fair to receive attribution.

**Comment by mthipparthi** [comment]
Sorry for that. It was just overlooked.The license is fixed as per issue.

**Comment by adieyal** [comment]
My apologies - I did not look carefully at the way you were using Wazimap. I thought that the project was a fork rather than being used as a library. Your original licence terms were perfect.
